name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN  }} ghcr.io
          docker build . --tag ghcr.io/sertzu/letf-frontend:prod
          docker push ghcr.io/sertzu/letf-frontend:prod
